# Generated by Django 3.2.4 on 2021-07-04 17:41

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='banner/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('mobile', models.CharField(max_length=10)),
                ('product_id', models.CharField(max_length=256)),
                ('product_name', models.CharField(max_length=256)),
                ('price', models.IntegerField(default=0)),
                ('img_url', models.CharField(blank=True, max_length=500)),
                ('qty', models.IntegerField()),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('order_amount', models.PositiveIntegerField(null=True)),
                ('order_number', models.CharField(blank=True, max_length=256)),
                ('transaction_id', models.CharField(blank=True, max_length=256)),
                ('payment_signature', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('profile_image', models.ImageField(blank=True, default='', upload_to='profile/')),
                ('token', models.CharField(blank=True, max_length=256, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecart.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', ckeditor.fields.RichTextField()),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('thumbnail', models.ImageField(blank=True, default='', upload_to='product/')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('category_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecart.category')),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecart.subcategory')),
            ],
        ),
    ]
