# Generated by Django 3.2.4 on 2021-07-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0002_auto_20210704_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='courier_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
