# Generated by Django 3.2.4 on 2021-07-04 19:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0003_auto_20210704_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publish_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
