# Generated by Django 3.2.4 on 2021-07-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0004_alter_product_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img1',
            field=models.ImageField(blank=True, default='', upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img2',
            field=models.ImageField(blank=True, default='', upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img3',
            field=models.ImageField(blank=True, default='', upload_to='product/'),
        ),
    ]
