# Generated by Django 3.2.4 on 2021-06-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0006_auto_20210607_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[(0, 'Select Color'), (1, 'White'), (2, 'Black'), (3, 'Gold'), (4, 'Royal'), (5, 'Navy'), (6, 'Maroon'), (7, 'Purple'), (8, 'Brown'), (9, 'Lime'), (10, 'Silver')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[(0, 'Select Size'), (1, 'XS'), (2, 'S'), (3, 'M'), (4, 'L'), (5, 'XL'), (6, 'XXL')], default='', max_length=1),
        ),
    ]
