# Generated by Django 3.2.4 on 2021-06-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0008_auto_20210607_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mrp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(),
        ),
    ]
