# Generated by Django 3.2.4 on 2021-06-16 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0011_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=256)),
                ('product_name', models.CharField(max_length=256)),
                ('qty', models.IntegerField()),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('order_amount', models.PositiveIntegerField()),
                ('order_number', models.CharField(max_length=256)),
                ('transaction_id', models.CharField(max_length=256)),
                ('payment_signature', models.CharField(max_length=256)),
            ],
        ),
    ]
