# Generated by Django 3.2.4 on 2021-06-16 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0015_alter_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
