# Generated by Django 3.2.4 on 2021-06-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0023_auto_20210616_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
