# Generated by Django 3.2.4 on 2021-06-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0024_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
