# Generated by Django 3.2.4 on 2021-06-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0027_auto_20210627_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='img_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
