# Generated by Django 3.2.4 on 2021-06-29 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0028_order_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
